### ISSUE TITLE
Script is giving me an error right at the start when i run it

### ISSUE THREAD

**Issue by Copperspikes** [giuliodondi/kOS-Shuttle_OPS1#2] opened 2023-10-07 04:15 UTC
I have set up the shuttle according to the mod and I am using your shuttle. When I run the shuttle.ks on the launch pad I get this error
![Screenshot 2023-10-07 001235](https://github.com/giuliodondi/kOS-Shuttle_OPS1/assets/68519868/b33cd57e-e680-462b-be36-7da0c9bb86bf)

This next picture is a picture of the flight screen where i believe that everything is set up correctly
![Screenshot 2023-10-07 001427](https://github.com/giuliodondi/kOS-Shuttle_OPS1/assets/68519868/5a9ff62d-d811-403d-b90b-3f8d076381ab)

I would appreciate if you have any insight as to why this error is occurring

**Comment by giuliodondi** [comment] 2023-10-08 22:55
The issue is a navigation function missing from the common library. 
This was puzzling to me because I remembered adding that function to the library code of the ascent script, 
But then I realised that the navigation library for the Shuttle reentry script might have been out of date by mistake, which then threw everything off since you're supposed to overwrite the common library files.

It's an error on my part, I apologise. I've tested and updated the source codes of both ascent and entry scripts and it sould be fixed now. Please download the latest versions of both scripts.

**Closed** 2023-10-15 23:58 UTC
