### ISSUE TITLE
i keep getting these errors when i run ops1 and 3

### ISSUE THREAD

**Issue by rocketman572** [giuliodondi/kOS-Shuttle_OPS1#20] opened 2024-08-03 23:35 UTC
![Screenshot 2024-08-02 154952](https://github.com/user-attachments/assets/d93a9ebc-0fa2-4ea9-95e0-1d60c47c0aab)
![Screenshot 2024-08-02 165346](https://github.com/user-attachments/assets/6f5506de-4ca7-4b9c-925c-229f0d6c97e2)

**Comment by giuliodondi** [comment] 2024-08-04 00:05
- please make sure that you installed the scripts in the correct folder
- make sure that you switch to volume 0 before running the script

If the issue persists, post screenshots of what your  ksp/Ships/Script folder looks like

**Comment by rocketman572** [comment] 2024-08-04 00:22
![Screenshot 2024-08-03 192057](https://github.com/user-attachments/assets/002a6bee-fc44-4d48-b738-8d7f51551e6f)
 same issue already set volume to 0 full directory is C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\Ships\Script

**Comment by giuliodondi** [comment] 2024-08-04 00:49
this looks weird to me: you're inside the 'Ships/Script' folder and yet you have another 'Ships' folder as well as a 'KSP' folder for some reason. And I don't see any of the launcher scripts, ops1.ks and ops3.ks.

Anyway this all points to an installation issue. I suggest you clean up this folder or even start over from a new KSP installation to sort things out. 

I'm closing down the issue because it's not a bug with the script itself. if you post proff that the script is correctly installed and yet the problem persists, I can reopen it

**Closed by giuliodondi** 2024-08-04 00:49 UTC
