### ISSUE TITLE
Issue for OPS1 Ascent

### ISSUE THREAD

**Issue by FlandreScarlet1** [giuliodondi/kOS-Shuttle_OPS1#7] opened 2024-01-07 19:13 UTC
![Kerbal Space Program Screenshot 2024 01 07 - 11 11 08 44](https://github.com/giuliodondi/kOS-Shuttle_OPS1/assets/142283370/ffd27a30-c69b-4b36-ab19-313f347db8dd)
for some reason the once the the srb are decoupled after 1:55 the main engines of the rs-25 switch off and im also targeting to intercept the mir space station which idk if thats the reason.

**Comment by giuliodondi** [comment] 2024-01-08 08:33
Do the main engines switch off **before** or **after** the script crashes with the error showed in your terminal?

Also, I'd like to recreate your scenario for testing. Please post here the contents of the launch script shuttle.ks that you ran, along with the parameters of your target station

**Comment by FlandreScarlet1** [comment] 2024-01-08 23:08
after the boosters separate the main engines shut down before the script crashes and the throttle automatically switches to zero automatically without me even touching anything on my keyboard. with the error showed in my terminal

**Comment by FlandreScarlet1** [comment] 2024-01-08 23:09
this was the script i used.

 @LAZYGLOBAL OFF.


//Launch Settings

GLOBAL target_orbit IS LEXICON (	
								"periapsis",30,
								"apoapsis",220,
								"cutoff alt",112,
								"inclination",40
).


// uncomment this line to trigger automatically an engine failure. Alternatively shutdown manually one of the engines 
//GLOBAL engine_failure_time IS 150.
//GLOBAL engine_failure_time IS 230.


//TAL site selection is now automatic. Uncomment this to select a specific TAL site
//GLOBAL TAL_site is "Zaragoza".


GLOBAL logdata Is true.


RUNPATH("0:/Shuttle_OPS1/src/ops1_launch").

**Comment by FlandreScarlet1** [comment] 2024-01-08 23:09
these are the logs i gotten
[Space Shuttle Discovery STS-91 RS-25A_log.csv](https://github.com/giuliodondi/kOS-Shuttle_OPS1/files/13867077/Space.Shuttle.Discovery.STS-91.RS-25A_log.csv)
[Space Shuttle Discovery STS-91 RS-25A_log_old.csv](https://github.com/giuliodondi/kOS-Shuttle_OPS1/files/13867078/Space.Shuttle.Discovery.STS-91.RS-25A_log_old.csv)

**Comment by FlandreScarlet1** [comment] 2024-01-08 23:11
the parameter of the Mir space station is exactly the 51.6 degrees but at night was at -51.6 in ksp RO 1.12.5 and was targeting 51.6 degrees

**Comment by FlandreScarlet1** [comment] 2024-01-08 23:13
and yes i launched from launchpad 39a in cape canaveral

**Comment by FlandreScarlet1** [comment] 2024-01-09 00:05
![Kerbal Space Program Screenshot 2024 01 08 - 16 04 15 89](https://github.com/giuliodondi/kOS-Shuttle_OPS1/assets/142283370/28444fd3-6c29-42be-a68b-97154f3d77c9)
![Kerbal Space Program Screenshot 2024 01 08 - 16 04 29 47](https://github.com/giuliodondi/kOS-Shuttle_OPS1/assets/142283370/c464e921-f6aa-4276-954c-662e537cda87)
![Kerbal Space Program Screenshot 2024 01 08 - 16 04 39 87](https://github.com/giuliodondi/kOS-Shuttle_OPS1/assets/142283370/c8bd4a3c-97a5-463c-8217-10617c7aa086)

**Comment by FlandreScarlet1** [comment] 2024-01-09 00:07
PE for mir is 354,000 meters and for AP its 374,000 meters the something in orbit like it used to be in real life

**Comment by giuliodondi** [comment] 2024-01-09 08:48
> these are the logs i gotten 

FYI these logs must be of some RTLS abort you did, based on the timestamps, the altitude and trust trends, as well as the latitude/longitude positions. so I'm not sure there will be something to learn from these

**Comment by FlandreScarlet1** [comment] 2024-01-12 06:24
> > these are the logs i gotten
> 
> FYI these logs must be of some RTLS abort you did, based on the timestamps, the altitude and thrust trends, as well as the latitude/longitude positions. so I'm not sure there will be something to learn from these.
> 
> I'll do my own tests and write back. In the meantime, please check if you have installed any third-party mod that controls throttle position, maybe when you cross an altitude threshold.

I checked if i had any third party installed avionics throttle controlled and i dont have any but i do have mechjeb which i use to for throttle not to be lowered to less than 5 percent

**Comment by giuliodondi** [comment] 2024-01-17 23:43
I was able to reproduce and find the problem, Nothing to do with throttle, it was the script that crashed first because of a targeting bug that only showed itself when a target vessel was selected.

I was able to perform successfully a nominal ascent to a target in a similar orbit to your scenario:
![screenshot180](https://github.com/giuliodondi/kOS-Shuttle_OPS1/assets/53257302/70c60aa1-694d-4a81-a32c-513e67e86ecc)
![screenshot181](https://github.com/giuliodondi/kOS-Shuttle_OPS1/assets/53257302/660e87e1-93b4-4e0e-a1f9-a753b339c195)

Please update the launch script files and test if it's fixed on your end as well. Take care that soon I'll be making furher changes here once I'm done working on the new Shuttle OPS3 script.

**Closed** 2024-01-25 22:35 UTC
